grpc.server.port=59091
kafka.topic.telemetry.sensors-topic=telemetry.sensors.v1
kafka.topic.telemetry.hubs-topic=telemetry.hubs.v1
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer