aggregator.kafka.consumer.shapshot.bootstrap-servers=localhost:9092
aggregator.kafka.consumer.shapshot.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
aggregator.kafka.consumer.shapshot.value-deserializer=ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
aggregator.kafka.consumer.shapshot.group-id=telemetry.analyzer.snapshot
aggregator.kafka.consumer.shapshot.enable-auto-commit=false
aggregator.kafka.consumer.shapshot.snapshot-topic=telemetry.snapshots.v1

aggregator.kafka.consumer.hub.bootstrap-servers=localhost:9092
aggregator.kafka.consumer.hub.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
aggregator.kafka.consumer.hub.value-deserializer=ru.yandex.practicum.kafka.deserializer.HubDeserializer
aggregator.kafka.consumer.hub.group-id=telemetry.analyzer.hub
aggregator.kafka.consumer.hub.enable-auto-commit=false
aggregator.kafka.consumer.hub.hub-topic=telemetry.hubs.v1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/test
spring.datasource.username=user
spring.datasource.password=123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.sql.init.mode=always

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext